services:
  vectorchord_db:
    image: tensorchord/vchord-postgres:pg18-v0.5.3
    command: [
      "postgres",
      "-c", "shared_buffers=4GB",
      "-c", "effective_cache_size=12GB",
      "-c", "work_mem=32MB",
      "-c", "maintenance_work_mem=4GB",
      "-c", "max_parallel_maintenance_workers=8",
      "-c", "max_worker_processes=8"
    ]
    shm_size: '8gb'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./vectorchord-init.sql:/docker-entrypoint-initdb.d/init.sql
      - vectorchord-data:/var/lib/postgresql/18/data

volumes:
  vectorchord-data:
