services:
  postgres_db:
    image: timescale/timescaledb-ha:pg17
    command: [
      "postgres",
      "-c", "shared_preload_libraries=timescaledb,vchord",
      "-c", "shared_buffers=4GB",
      "-c", "effective_cache_size=12GB",
      "-c", "work_mem=32MB",
      "-c", "maintenance_work_mem=4GB",
      "-c", "max_parallel_maintenance_workers=8",
      "-c", "max_worker_processes=8"
    ]
    shm_size: '8gb'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
